export var terrainMap = [
    [ "r", "r", "r", "r", "r", "r", "r", "r", "r"],
    ["r" ,"gr", "gr", "gr", "gr", "gr", "gr", "gr", "r"],
    ["r" ,"gr", "gr", "gr", "gr", "gr", "gr", "gr", "r"],
    ["r" ,"gr", "gr", "gr", "gr", "gr", "gr", "gr", "r"],
    ["r" ,"r",  "r",  "gr", "gr", "gr", "gr", "gr", "r"],
    ["r" ,"gr",   "r",  "gr", "gr", "gr", "gr", "gr", "r"],
    ["r" ,"gr",   "r",  "r", "r", "r", "r", "r", "r"],
    ["r" ,"d",   "r",  "gr", "gr", "gr", "gr", "gr", "r"],
    ["r" ,"gr",   "r",  "gr", "gr", "gr", "gr", "gr", "r"],
    ["r" ,"r",   "r",  "r", "r", "r", "r", "r", "r"],
  ];

  // export var terrainMap = [
  //   [ "r", "r", "r", "r", "r", "r", "r", "r", "r", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["r" ,"gr", "gr", "gr", "gr", "gr", "gr", "gr", "r", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["r" ,"gr", "gr", "gr", "gr", "gr", "gr", "gr", "r", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["r" ,"gr", "gr", "gr", "gr", "gr", "gr", "gr", "r", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["r" ,"r",  "r",  "gr", "gr", "gr", "gr", "gr", "r", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["r" ,"gr",   "r",  "gr", "gr", "gr", "gr", "gr", "r", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["r" ,"gr",   "r",  "r", "r", "r", "r", "r", "r", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["r" ,"d",   "r",  "gr", "gr", "gr", "gr", "gr", "r", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["r" ,"gr",   "r",  "gr", "gr", "gr", "gr", "gr", "r", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["r" ,"r",   "r",  "r", "r", "r", "r", "r", "r", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["gr" ,"gr",   "gr",  "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["gr" ,"gr",   "gr",  "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["gr" ,"gr",   "gr",  "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["gr" ,"gr",   "gr",  "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["gr" ,"gr",   "gr",  "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["gr" ,"gr",   "gr",  "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["gr" ,"gr",   "gr",  "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["gr" ,"gr",   "gr",  "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["gr" ,"gr",   "gr",  "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  //   ["gr" ,"gr",   "gr",  "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr", "gr"],
  // ];